project:
  type: website
  output-dir: docs

website:
  title: "MuonBlog"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/muon01_
      - icon: youtube
        href: https://youtube.com/@MuonCh
      - icon: twitch
        href: https://twitch.tv/muon01
      - icon: github
        href: https://github.com/muon01

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

